# -*- coding: utf-8 -*-
"""Data Wrangling and Visualization .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmuYGu_o4Sx5EHqJRjkcl4Fiq3U0a-nE
"""

# STUDENT DATASET
#importing libraries & Loading Dataset
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Load the dataset
file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

print("✅ Dataset loaded successfully!")
display(df.head())
print("\nDataset Shape:", df.shape)
print("\nColumn Names:", df.columns.tolist())
print("\nDataset Info:")
df.info()

# ======================================
# ADVANCED PREPROCESSING PIPELINE
# ======================================

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

# -------------------------
# Load dataset
# -------------------------

# Correcting the file path to point to the dataset in Google Drive
file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

print("📌 Initial Dataset loaded for preprocessing.")

# -------------------------
# Missing Value Summary
# -------------------------

print("\n📌 Missing Values Before Preprocessing:")
print(df.isnull().sum())

# ======================================
# 1️⃣ HANDLE MISSING VALUES
# ======================================

# Numeric columns → fill with median
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns → fill with mode
cat_cols = df.select_dtypes(include=['object']).columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("\n📌 Missing Values After Filling:")
print(df.isnull().sum())

# ======================================
# 2️⃣ OUTLIER REMOVAL (IQR METHOD)
# ======================================

def remove_outliers_IQR(data, col):
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return data[(data[col] >= lower) & (data[col] <= upper)]

for col in num_cols:
    df = remove_outliers_IQR(df, col)

print("\n📌 After Removing Outliers:")
print(df.describe())

# ======================================
# 3️⃣ LABEL ENCODING (for categorical columns)
# ======================================

le = LabelEncoder()

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

print("\n📌 After Label Encoding:")
# display(df.head()) # Removed duplicate output

# ======================================
# 4️⃣ FEATURE SCALING (Min-Max Normalization)
# ======================================

scaler = MinMaxScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

print("\n📌 After Feature Scaling:")
# display(df.head()) # Removed duplicate output

# ======================================
# 5️⃣ SAVE CLEANED DATASET
# ======================================

df.to_csv("student_performance_cleaned_advanced.csv", index=False)

print("\n🎉 Advanced Preprocessing Completed!")
print("📁 File saved as: student_performance_cleaned_advanced.csv")

!pip install altair vega_datasets

##vizualization##

import pandas as pd
import matplotlib.pyplot as plt

file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

plt.figure(figsize=(8,5))
plt.hist(df["OverallScore"], bins=20)
plt.title("Distribution of Overall Scores")
plt.xlabel("Score")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df["StudyHours"], bins=20)
plt.title("Distribution of Study Hours")
plt.xlabel("Hours")
plt.ylabel("Count")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

plt.figure(figsize=(10,7))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

plt.figure(figsize=(8,5))
sns.boxplot(df["FinalScore"])
plt.title("Final Score Outliers")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

plt.figure(figsize=(8,5))
sns.barplot(x="Gender", y="OverallScore", data=df)
plt.title("Overall Score by Gender")
plt.show()

import pandas as pd
import plotly.express as px

file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

fig = px.scatter(
    df,
    x="StudyHours",
    y="OverallScore",
    color="Gender",
    title="Interactive: Study Hours vs Overall Score",
    hover_data=["Class", "AttendanceRate"]
)
fig.show()

import pandas as pd
import plotly.express as px

file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

fig = px.scatter_3d(
    df,
    x="StudyHours",
    y="AttendanceRate",
    z="OverallScore",
    color="Gender",
    title="3D Interactive: Study Hours vs Attendance vs Score"
)
fig.show()

#questionnaire#

from google.colab import drive
drive.mount('/content/drive')
print("✅ Google Drive mounted successfully!")

#Q1 — What is the distribution of students' Overall Score?
import plotly.express as px

fig = px.histogram(df, x="OverallScore", nbins=20,
                   title="Distribution of Overall Score",
                   marginal="box", color="Gender")
fig.show()

#Q2 — How does average Attendance Rate vary across classes?
att_class = df.groupby("Class")["AttendanceRate"].mean().reset_index()

fig = px.bar(att_class, x="Class", y="AttendanceRate",
             title="Average Attendance Rate per Class",
             color="Class")
fig.show()

#Q3 — What is the relationship between Midterm Score and Final Score?
fig = px.scatter(df, x="MidtermScore", y="FinalScore",
                 color="Gender",
                 title="Relationship Between Midterm and Final Scores")
fig.show()

#Q4 How are the various factors in the dataset related to each other?
import plotly.figure_factory as ff
import pandas as pd
import numpy as np
from google.colab import drive

# Ensure Google Drive is mounted for file access
drive.mount('/content/drive', force_remount=True)

# Ensure df is loaded within this cell's scope
file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

# 1. Select ONLY numeric columns
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# 2. Compute correlation properly
corr = numeric_df.corr()

# 3. Remove ANY rows/cols with all NaN (safety)
corr = corr.dropna(axis=0, how='all')
corr = corr.dropna(axis=1, how='all')

# Round correlation values for better annotation display
corr_rounded = corr.round(2);

# 4. Create a clean annotated heatmap
fig = ff.create_annotated_heatmap(
    z=corr.values,
    x=list(corr.columns),
    y=list(corr.columns),
    annotation_text=corr_rounded.values, # Use rounded values for annotations
    colorscale='Viridis',
    showscale=True
)

fig.update_layout(
    title="Correlation Heatmap",
    xaxis=dict(title="Attributes"),
    yaxis=dict(title="Attributes"),
    width=800,  # Increased width for better spacing
    height=700  # Increased height for better spacing
)

fig.show()

#Q5 — How does attendance percentage influence Overall Score (CGPA equivalent)?
import pandas as pd
import plotly.express as px

# Ensure df is loaded in this cell's scope
file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

fig = px.scatter(df, x="AttendanceRate", y="OverallScore",
                 color="Class", # Using 'Class' as equivalent to 'Department_Branch'
                 title="Relationship Between Attendance Rate and Overall Score",
                 trendline="ols")
fig.show()

#Q6  How does CGPA vary among branches?
import pandas as pd
import plotly.express as px

# Ensure df is loaded in this cell's scope
file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

fig = px.box(df, x="Class", y="OverallScore",
             title="Overall Score Distribution per Class",
             color="Class")
fig.show()

#Q7 — Who are the top 15 students based on CGPA?
import pandas as pd
import plotly.express as px

# Ensure df is loaded in this cell's scope
file_path = '/content/drive/MyDrive/student_performance_dataset_link_version.csv'
df = pd.read_csv(file_path)

top15 = df.sort_values(by="OverallScore", ascending=False).head(15)

fig = px.bar(top15, x="StudentID", y="OverallScore",
             title="Top 15 Students by Overall Score",
             color="Class") # Assuming 'Class' is equivalent to 'Department_Branch'
fig.show()